name: code checks

on: push

jobs:
  checks:
    name: run checks
    runs-on: ubuntu-18.04

    steps:
      - name: set up python 3.6.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.10

      - name: install dependencies
        run: pip install bandit black flake8

      - name: checkout code
        uses: actions/checkout@v2

      - name: run bandit security checks
        run: bandit -ll -r caldp

      - name: run black style checks
        run: black --check caldp caldp/tests

      - name: run flake8 python lint checks
        run: flake8 --count --max-line-length=120 --exclude docs
